### ISSUE TITLE
bantu installnya min:'

### ISSUE THREAD

**Issue by MSI0072** [khavitidala/WhatsApp-ChatBot-of-Al-Qur-an#5]
![image](https://user-images.githubusercontent.com/63404067/96516358-36919300-1291-11eb-9d9c-e2d7d2e879bd.png)

**Comment by khavitidala** [comment]
cobain pull versi terbaru, udah saya update dependenciesnya ke versi terbaru. Lalu, pastikan di index.js baris ke-20
> `serverOption.executablePath = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe`

coba sesuaikan dgn path tempat executable chrome berada

**Comment by MSI0072** [comment]
> cobain pull versi terbaru, udah saya update dependenciesnya ke versi terbaru. Lalu, pastikan di index.js baris ke-20
> 
> > `serverOption.executablePath = 'C:\\Program Files (x86)\\Google\\Chrome\\Application\\chrome.exe`
> 
> coba sesuaikan dgn path tempat executable chrome berada

![image](https://user-images.githubusercontent.com/63404067/97862851-a0517880-1d38-11eb-833b-658410a03945.png)


dahh bisa min makasi
